name: Build and Publish PersonalQuery
on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src/electron
    strategy:
      matrix:
        include:
          #- os: windows-latest FIXME
          - os: macos-latest
            mac_arch: arm64
          - os: macos-latest
            mac_arch: x64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      # ------------------------------------------------
      # Backend build (runs BEFORE Electron packaging)
      # ------------------------------------------------

      - name: Install backend dependencies
        working-directory: src/py-backend
        run: poetry install --no-root

      - name: Build backend executable (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: src/py-backend
        run: poetry run pyinstaller personalquery-backend.spec
        env:
          LANGSMITH_TRACING: false
          LANGSMITH_ENDPOINT: https://api.smith.langchain.com
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_PROJECT: personalQuery
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Sign backend executable with Trusted Signing (Windows)
        if: matrix.os == 'windows-latest'
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
          files-folder: src\py-backend\dist
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.digicert.com
          timestamp-digest: SHA256

      - name: Import code signing certificate (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "${CSC_LINK}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${CSC_KEY_PASSWORD}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        env:
          CSC_LINK: ${{ secrets.SCS_HASH }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Build backend executable with PyInstaller and codesign (macOS)
        if: startsWith(matrix.os, 'macos')
        working-directory: src/py-backend
        run: |
          SIGN_ID=$(security find-identity -v -p codesigning | grep "Developer ID Application" | head -n1 | awk -F\" '{print $2}')
          echo "Using signing identity: $SIGN_ID"

          poetry run pyinstaller personalquery-backend.spec \
            --codesign-identity "$SIGN_ID" \
            --osx-entitlements-file ../build/entitlements.mac.plist
        env:
          LANGSMITH_TRACING: false
          LANGSMITH_ENDPOINT: https://api.smith.langchain.com
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_PROJECT: personalQuery
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Verify macOS signature
        if: startsWith(matrix.os, 'macos')
        working-directory: src/py-backend
        run: codesign --verify --deep --strict --verbose=4 dist/pq-backend

      # ------------------------------------------------
      # Electron build (as in original workflow)
      # ------------------------------------------------

      - name: Install Electron dependencies
        run: npm ci

      - name: Build Electron App
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            if [ "${{ matrix.mac_arch }}" == "arm64" ]; then
              npm run build:mac:arm64
            else
              npm run build:mac:x64
            fi
          else
            npm run build
          fi
        env:
          MAC_ARCH_TYPE: ${{ matrix.mac_arch == 'arm64' && 'AppleSilicon' || 'Intel' }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          AZURE_PUBLISHER_NAME: ${{ vars.AZURE_PUBLISHER_NAME }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_CODE_SIGNING_NAME: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
          AZURE_CERT_PROFILE_NAME: ${{ secrets.AZURE_CERT_PROFILE_NAME }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
